### PR TITLE
Revised NPCs -- Spanish language (Part 1)

### PR DESCRIPTION
**Pull request by ToklaX**
This PR:
- [x] Checked & retranslated all shopkeepers based on en_us files.
- [x] Checked & retranslated all trainers based on en_us files.

Future PRs:
- [ ] To translate all npc from Gyms into spanish.
- [ ] To review & retranslate villagers.

### CODE REVIEW

**Comment by lightningo7** [comment]
This is not the place for this. you want to go to this github to help with translating. https://github.com/Pixelmon/Pixelmon-Language

**Comment by ToklaX** [comment]
Hi @lightningo7 , I know that the main repositorie from the mod
 its https://github.com/Pixelmon/Pixelmon-Language because im already helping with the spanish files.
But I think that this is the correct place for this PR, i've edited the NPC spanish files as pixelmon's Devs said months ago from the NPC project repo. And I suppose that this is a very completed repo where you can also continue translations. Idk, if im wrong just tell me and i will close the PR as soon as i can.

**Comment by lightningo7** [comment]
This github is being used for the Pixelmon gyms currently. I believe everything else has another location to go to unless otherwise stated by the developers.

**Comment by ToklaX** [comment]
Well, if any dev can clarify this, I'd appreciate it.

**Comment by MrMasochism** [comment]
You are right toklax that translations for gyms will need to go here

**Pull request merged**
